const siteSettings = [
  {
    name: '',
    amazon: '',
    comicJp: '',
    comicJpImage: '',
    unext: '',
    unextImage: '',
    ebookjapan: '',
    ebookjapanImage: '',
    cimoa: '',
    cimoaImage: '',
    mangaokoku: '',
  },
  {
    name: '',
    amazon: '',
    comicJp: '',
    comicJpImage: '',
    unext: '',
    unextImage: '',
    ebookjapan: '',
    ebookjapanImage: '',
    cimoa: '',
    cimoaImage: '',
    mangaokoku: '',
  },
]
